// Code generated by protoc-gen-go. DO NOT EDIT.
// source: register.proto

package register

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SlaveConfig struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlaveConfig) Reset()         { *m = SlaveConfig{} }
func (m *SlaveConfig) String() string { return proto.CompactTextString(m) }
func (*SlaveConfig) ProtoMessage()    {}
func (*SlaveConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1303fe8288f4efb6, []int{0}
}

func (m *SlaveConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlaveConfig.Unmarshal(m, b)
}
func (m *SlaveConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlaveConfig.Marshal(b, m, deterministic)
}
func (m *SlaveConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlaveConfig.Merge(m, src)
}
func (m *SlaveConfig) XXX_Size() int {
	return xxx_messageInfo_SlaveConfig.Size(m)
}
func (m *SlaveConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SlaveConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SlaveConfig proto.InternalMessageInfo

func (m *SlaveConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *SlaveConfig) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SlaveConfig) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SlaveRegisterStatus struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlaveRegisterStatus) Reset()         { *m = SlaveRegisterStatus{} }
func (m *SlaveRegisterStatus) String() string { return proto.CompactTextString(m) }
func (*SlaveRegisterStatus) ProtoMessage()    {}
func (*SlaveRegisterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1303fe8288f4efb6, []int{1}
}

func (m *SlaveRegisterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlaveRegisterStatus.Unmarshal(m, b)
}
func (m *SlaveRegisterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlaveRegisterStatus.Marshal(b, m, deterministic)
}
func (m *SlaveRegisterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlaveRegisterStatus.Merge(m, src)
}
func (m *SlaveRegisterStatus) XXX_Size() int {
	return xxx_messageInfo_SlaveRegisterStatus.Size(m)
}
func (m *SlaveRegisterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SlaveRegisterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SlaveRegisterStatus proto.InternalMessageInfo

func (m *SlaveRegisterStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SlaveConfig)(nil), "SlaveConfig")
	proto.RegisterType((*SlaveRegisterStatus)(nil), "SlaveRegisterStatus")
}

func init() {
	proto.RegisterFile("register.proto", fileDescriptor_1303fe8288f4efb6)
}

var fileDescriptor_1303fe8288f4efb6 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4e, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0x92,
	0x4a, 0xde, 0x5c, 0xdc, 0xc1, 0x39, 0x89, 0x65, 0xa9, 0xce, 0xf9, 0x79, 0x69, 0x99, 0xe9, 0x42,
	0x42, 0x5c, 0x2c, 0x19, 0xf9, 0xc5, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36,
	0x48, 0xac, 0x20, 0xbf, 0xa8, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0xcc, 0x16, 0x12,
	0xe1, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd, 0x93, 0x60, 0x06, 0x2b, 0x84, 0x70, 0x94, 0xf4, 0xb9,
	0x84, 0xc1, 0x86, 0x05, 0x41, 0x1d, 0x10, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x2c, 0x24, 0xc1, 0xc5,
	0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x0a, 0x35, 0x17, 0xc6, 0x35, 0x72, 0xe1, 0xe2, 0x80,
	0xa9, 0x15, 0xb2, 0xe0, 0x12, 0x80, 0xb1, 0xfd, 0x52, 0xcb, 0xc1, 0xe6, 0x08, 0xf1, 0xe8, 0x21,
	0x39, 0x4e, 0x4a, 0x44, 0x0f, 0x8b, 0xe9, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xaf, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x2a, 0x52, 0x4b, 0x3f, 0xf9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterClient interface {
	RegisterNewSlave(ctx context.Context, in *SlaveConfig, opts ...grpc.CallOption) (*SlaveRegisterStatus, error)
}

type registerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterClient(cc grpc.ClientConnInterface) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) RegisterNewSlave(ctx context.Context, in *SlaveConfig, opts ...grpc.CallOption) (*SlaveRegisterStatus, error) {
	out := new(SlaveRegisterStatus)
	err := c.cc.Invoke(ctx, "/Register/RegisterNewSlave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServer is the server API for Register service.
type RegisterServer interface {
	RegisterNewSlave(context.Context, *SlaveConfig) (*SlaveRegisterStatus, error)
}

// UnimplementedRegisterServer can be embedded to have forward compatible implementations.
type UnimplementedRegisterServer struct {
}

func (*UnimplementedRegisterServer) RegisterNewSlave(ctx context.Context, req *SlaveConfig) (*SlaveRegisterStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewSlave not implemented")
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_RegisterNewSlave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).RegisterNewSlave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Register/RegisterNewSlave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).RegisterNewSlave(ctx, req.(*SlaveConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNewSlave",
			Handler:    _Register_RegisterNewSlave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register.proto",
}
